
export const countries = [
  { name: 'United States', code: 'USA', phone: '1', flag: '🇺🇸' },
  { name: 'Afghanistan', code: 'AFG', phone: '93', flag: '🇦🇫' },
  { name: 'Albania', code: 'ALB', phone: '355', flag: '🇦🇱' },
  { name: 'Algeria', code: 'DZA', phone: '213', flag: '🇩🇿' },
  { name: 'Andorra', code: 'AND', phone: '376', flag: '🇦🇩' },
  { name: 'Angola', code: 'AGO', phone: '244', flag: '🇦🇴' },
  { name: 'Argentina', code: 'ARG', phone: '54', flag: '🇦🇷' },
  { name: 'Armenia', code: 'ARM', phone: '374', flag: '🇦🇲' },
  { name: 'Australia', code: 'AUS', phone: '61', flag: '🇦🇺' },
  { name: 'Austria', code: 'AUT', phone: '43', flag: '🇦🇹' },
  { name: 'Azerbaijan', code: 'AZE', phone: '994', flag: '🇦🇿' },
  { name: 'Bahamas', code: 'BHS', phone: '1242', flag: '🇧🇸' },
  { name: 'Bahrain', code: 'BHR', phone: '973', flag: '🇧🇭' },
  { name: 'Bangladesh', code: 'BGD', phone: '880', flag: '🇧🇩' },
  { name: 'Barbados', code: 'BRB', phone: '1246', flag: '🇧🇧' },
  { name: 'Belarus', code: 'BLR', phone: '375', flag: '🇧🇾' },
  { name: 'Belgium', code: 'BEL', phone: '32', flag: '🇧🇪' },
  { name: 'Belize', code: 'BLZ', phone: '501', flag: '🇧🇿' },
  { name: 'Benin', code: 'BEN', phone: '229', flag: '🇧🇯' },
  { name: 'Bhutan', code: 'BTN', phone: '975', flag: '🇧🇹' },
  { name: 'Bolivia', code: 'BOL', phone: '591', flag: '🇧🇴' },
  { name: 'Brazil', code: 'BRA', phone: '55', flag: '🇧🇷' },
  { name: 'Brunei', code: 'BRN', phone: '673', flag: '🇧🇳' },
  { name: 'Bulgaria', code: 'BGR', phone: '359', flag: '🇧🇬' },
  { name: 'Burkina Faso', code: 'BFA', phone: '226', flag: '🇧🇫' },
  { name: 'Burundi', code: 'BDI', phone: '257', flag: '🇧🇮' },
  { name: 'Cambodia', code: 'KHM', phone: '855', flag: '🇰🇭' },
  { name: 'Cameroon', code: 'CMR', phone: '237', flag: '🇨🇲' },
  { name: 'Canada', code: 'CAN', phone: '1', flag: '🇨🇦' },
  { name: 'Chad', code: 'TCD', phone: '235', flag: '🇹🇩' },
  { name: 'Chile', code: 'CHL', phone: '56', flag: '🇨🇱' },
  { name: 'China', code: 'CHN', phone: '86', flag: '🇨🇳' },
  { name: 'Colombia', code: 'COL', phone: '57', flag: '🇨🇴' },
  { name: 'Congo', code: 'COG', phone: '242', flag: '🇨🇬' },
  { name: 'Costa Rica', code: 'CRI', phone: '506', flag: '🇨🇷' },
  { name: 'Croatia', code: 'HRV', phone: '385', flag: '🇭🇷' },
  { name: 'Cuba', code: 'CUB', phone: '53', flag: '🇨🇺' },
  { name: 'Cyprus', code: 'CYP', phone: '357', flag: '🇨🇾' },
  { name: 'Czech Republic', code: 'CZE', phone: '420', flag: '🇨🇿' },
  { name: 'Denmark', code: 'DNK', phone: '45', flag: '🇩🇰' },
  { name: 'Ecuador', code: 'ECU', phone: '593', flag: '🇪🇨' },
  { name: 'Egypt', code: 'EGY', phone: '20', flag: '🇪🇬' },
  { name: 'Estonia', code: 'EST', phone: '372', flag: '🇪🇪' },
  { name: 'Ethiopia', code: 'ETH', phone: '251', flag: '🇪🇹' },
  { name: 'Fiji', code: 'FJI', phone: '679', flag: '🇫🇯' },
  { name: 'Finland', code: 'FIN', phone: '358', flag: '🇫🇮' },
  { name: 'France', code: 'FRA', phone: '33', flag: '🇫🇷' },
  { name: 'Gabon', code: 'GAB', phone: '241', flag: '🇬🇦' },
  { name: 'Georgia', code: 'GEO', phone: '995', flag: '🇬🇪' },
  { name: 'Germany', code: 'DEU', phone: '49', flag: '🇩🇪' },
  { name: 'Ghana', code: 'GHA', phone: '233', flag: '🇬🇭' },
  { name: 'Greece', code: 'GRC', phone: '30', flag: '🇬🇷' },
  { name: 'Greenland', code: 'GRL', phone: '299', flag: '🇬🇱' },
  { name: 'Guatemala', code: 'GTM', phone: '502', flag: '🇬🇹' },
  { name: 'Guinea', code: 'GIN', phone: '224', flag: '🇬🇳' },
  { name: 'Haiti', code: 'HTI', phone: '509', flag: '🇭🇹' },
  { name: 'Honduras', code: 'HND', phone: '504', flag: '🇭🇳' },
  { name: 'Hong Kong', code: 'HKG', phone: '852', flag: '🇭🇰' },
  { name: 'Hungary', code: 'HUN', phone: '36', flag: '🇭🇺' },
  { name: 'Iceland', code: 'ISL', phone: '354', flag: '🇮🇸' },
  { name: 'India', code: 'IND', phone: '91', flag: '🇮🇳' },
  { name: 'Indonesia', code: 'IDN', phone: '62', flag: '🇮🇩' },
  { name: 'Iran', code: 'IRN', phone: '98', flag: '🇮🇷' },
  { name: 'Iraq', code: 'IRQ', phone: '964', flag: '🇮🇶' },
  { name: 'Ireland', code: 'IRL', phone: '353', flag: '🇮🇪' },
  { name: 'Israel', code: 'ISR', phone: '972', flag: '🇮🇱' },
  { name: 'Italy', code: 'ITA', phone: '39', flag: '🇮🇹' },
  { name: 'Jamaica', code: 'JAM', phone: '1876', flag: '🇯🇲' },
  { name: 'Japan', code: 'JPN', phone: '81', flag: '🇯🇵' },
  { name: 'Jordan', code: 'JOR', phone: '962', flag: '🇯🇴' },
  { name: 'Kazakhstan', code: 'KAZ', phone: '7', flag: '🇰🇿' },
  { name: 'Kenya', code: 'KEN', phone: '254', flag: '🇰🇪' },
  { name: 'Kuwait', code: 'KWT', phone: '965', flag: '🇰🇼' },
  { name: 'Kyrgyzstan', code: 'KGZ', phone: '996', flag: '🇰🇬' },
  { name: 'Latvia', code: 'LVA', phone: '371', flag: '🇱🇻' },
  { name: 'Lebanon', code: 'LBN', phone: '961', flag: '🇱🇧' },
  { name: 'Liberia', code: 'LBR', phone: '231', flag: '🇱🇷' },
  { name: 'Libya', code: 'LBY', phone: '218', flag: '🇱🇾' },
  { name: 'Liechtenstein', code: 'LIE', phone: '423', flag: '🇱🇮' },
  { name: 'Lithuania', code: 'LTU', phone: '370', flag: '🇱🇹' },
  { name: 'Luxembourg', code: 'LUX', phone: '352', flag: '🇱🇺' },
  { name: 'Madagascar', code: 'MDG', phone: '261', flag: '🇲🇬' },
  { name: 'Malawi', code: 'MWI', phone: '265', flag: '🇲🇼' },
  { name: 'Malaysia', code: 'MYS', phone: '60', flag: '🇲🇾' },
  { name: 'Maldives', code: 'MDV', phone: '960', flag: '🇲🇻' },
  { name: 'Mali', code: 'MLI', phone: '223', flag: '🇲🇱' },
  { name: 'Malta', code: 'MLT', phone: '356', flag: '🇲🇹' },
  { name: 'Mexico', code: 'MEX', phone: '52', flag: '🇲🇽' },
  { name: 'Monaco', code: 'MCO', phone: '377', flag: '🇲🇨' },
  { name: 'Mongolia', code: 'MNG', phone: '976', flag: '🇲🇳' },
  { name: 'Montenegro', code: 'MNE', phone: '382', flag: '🇲🇪' },
  { name: 'Morocco', code: 'MAR', phone: '212', flag: '🇲🇦' },
  { name: 'Mozambique', code: 'MOZ', phone: '258', flag: '🇲🇿' },
  { name: 'Myanmar', code: 'MMR', phone: '95', flag: '🇲🇲' },
  { name: 'Namibia', code: 'NAM', phone: '264', flag: '🇳🇦' },
  { name: 'Nepal', code: 'NPL', phone: '977', flag: '🇳🇵' },
  { name: 'Netherlands', code: 'NLD', phone: '31', flag: '🇳🇱' },
  { name: 'New Zealand', code: 'NZL', phone: '64', flag: '🇳🇿' },
  { name: 'Nicaragua', code: 'NIC', phone: '505', flag: '🇳🇮' },
  { name: 'Niger', code: 'NER', phone: '227', flag: '🇳🇪' },
  { name: 'Nigeria', code: 'NGA', phone: '234', flag: '🇳🇬' },
  { name: 'North Korea', code: 'PRK', phone: '850', flag: '🇰🇵' },
  { name: 'Norway', code: 'NOR', phone: '47', flag: '🇳🇴' },
  { name: 'Oman', code: 'OMN', phone: '968', flag: '🇴🇲' },
  { name: 'Pakistan', code: 'PAK', phone: '92', flag: '🇵🇰' },
  { name: 'Panama', code: 'PAN', phone: '507', flag: '🇵🇦' },
  { name: 'Papua New Guinea', code: 'PNG', phone: '675', flag: '🇵🇬' },
  { name: 'Paraguay', code: 'PRY', phone: '595', flag: '🇵🇾' },
  { name: 'Peru', code: 'PER', phone: '51', flag: '🇵🇪' },
  { name: 'Philippines', code: 'PHL', phone: '63', flag: '🇵🇭' },
  { name: 'Poland', code: 'POL', phone: '48', flag: '🇵🇱' },
  { name: 'Portugal', code: 'PRT', phone: '351', flag: '🇵🇹' },
  { name: 'Qatar', code: 'QAT', phone: '974', flag: '🇶🇦' },
  { name: 'Romania', code: 'ROU', phone: '40', flag: '🇷🇴' },
  { name: 'Russia', code: 'RUS', phone: '7', flag: '🇷🇺' },
  { name: 'Rwanda', code: 'RWA', phone: '250', flag: '🇷🇼' },
  { name: 'Saudi Arabia', code: 'SAU', phone: '966', flag: '🇸🇦' },
  { name: 'Senegal', code: 'SEN', phone: '221', flag: '🇸🇳' },
  { name: 'Serbia', code: 'SRB', phone: '381', flag: '🇷🇸' },
  { name: 'Singapore', code: 'SGP', phone: '65', flag: '🇸🇬' },
  { name: 'Slovakia', code: 'SVK', phone: '421', flag: '🇸🇰' },
  { name: 'Slovenia', code: 'SVN', phone: '386', flag: '🇸🇮' },
  { name: 'Somalia', code: 'SOM', phone: '252', flag: '🇸🇴' },
  { name: 'South Africa', code: 'ZAF', phone: '27', flag: '🇿🇦' },
  { name: 'South Korea', code: 'KOR', phone: '82', flag: '🇰🇷' },
  { name: 'Spain', code: 'ESP', phone: '34', flag: '🇪🇸' },
  { name: 'Sri Lanka', code: 'LKA', phone: '94', flag: '🇱🇰' },
  { name: 'Sudan', code: 'SDN', phone: '249', flag: '🇸🇩' },
  { name: 'Sweden', code: 'SWE', phone: '46', flag: '🇸🇪' },
  { name: 'Switzerland', code: 'CHE', phone: '41', flag: '🇨🇭' },
  { name: 'Syria', code: 'SYR', phone: '963', flag: '🇸🇾' },
  { name: 'Taiwan', code: 'TWN', phone: '886', flag: '🇹🇼' },
  { name: 'Tajikistan', code: 'TJK', phone: '992', flag: '🇹🇯' },
  { name: 'Tanzania', code: 'TZA', phone: '255', flag: '🇹🇿' },
  { name: 'Thailand', code: 'THA', phone: '66', flag: '🇹🇭' },
  { name: 'Togo', code: 'TGO', phone: '228', flag: '🇹🇬' },
  { name: 'Trinidad and Tobago', code: 'TTO', phone: '1868', flag: '🇹🇹' },
  { name: 'Tunisia', code: 'TUN', phone: '216', flag: '🇹🇳' },
  { name: 'Turkey', code: 'TUR', phone: '90', flag: '🇹🇷' },
  { name: 'Turkmenistan', code: 'TKM', phone: '993', flag: '🇹🇲' },
  { name: 'Uganda', code: 'UGA', phone: '256', flag: '🇺🇬' },
  { name: 'Ukraine', code: 'UKR', phone: '380', flag: '🇺🇦' },
  { name: 'United Arab Emirates', code: 'ARE', phone: '971', flag: '🇦🇪' },
  { name: 'United Kingdom', code: 'GBR', phone: '44', flag: '🇬🇧' },
  { name: 'Uruguay', code: 'URY', phone: '598', flag: '🇺🇾' },
  { name: 'Uzbekistan', code: 'UZB', phone: '998', flag: '🇺🇿' },
  { name: 'Venezuela', code: 'VEN', phone: '58', flag: '🇻🇪' },
  { name: 'Vietnam', code: 'VNM', phone: '84', flag: '🇻🇳' },
  { name: 'Yemen', code: 'YEM', phone: '967', flag: '🇾🇪' },
  { name: 'Zambia', code: 'ZMB', phone: '260', flag: '🇿🇲' },
  { name: 'Zimbabwe', code: 'ZWE', phone: '263', flag: '🇿🇼' }
];

