
project_id = "qkcecnyzzvrdctdrlndg"

[functions.plaid-create-link-token]
verify_jwt = true

[functions.plaid-exchange-public-token]
verify_jwt = true

[functions.plaid-sync-transactions]
verify_jwt = true

[functions.plaid-get-accounts]
verify_jwt = true

[functions.plaid-get-transactions]
verify_jwt = true

[functions.plaid-delete-item]
verify_jwt = true
