// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkcecnyzzvrdctdrlndg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrY2Vjbnl6enZyZGN0ZHJsbmRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDQyNzQsImV4cCI6MjA2MDU4MDI3NH0.n9NVIx_cKRqGLbDCuEvkD2D4iumpkQ4_RpOP3Rt4hd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);